#!/bin/bash

[ -z "$*" ] && echo -e "\n\n\t\tUso: $(basename "$0") [LISTA] [ENDPOINT] [COOK1] [INICIAR_EM]" && exit;

POST_TO="$2"
SALVAR_EM="collect_$RANDOM.csv"
COOKIE="$3"
[ -z "$4" ] && INICIAR=0 || INICIAR=$4;

THREADS=30
THREAD_COUNTER=0

linha_n=0
while IFS= read -r consul_link
do
	let "linha_n+=1"
	[ "$linha_n" -lt "$INICIAR" ] && continue;
	[ -f "$PWD/movv" ] && break;

	let "THREAD_COUNTER+=1"
	[ "$THREAD_COUNTER" -le "$THREADS" ] && continue; 
	LINKS="$LINKS $consul_link"

	for link in $LINKS; do
		curl -ks \
		--cookie "ASP.NET_SessionId=$COOKIE" "$link" | ./html_para_csv "$SALVAR_EM" "$POST_TO" &
	done

	THREAD_COUNTER=0
	LINKS=""

	sleep 27
done < "$CONSUL_LINKS"
